# Titanic - Machine Learning From Disaster

https://www.youtube.com/watch?v=3gK_2XdjOdY

### Importing

In [225]:
import os
for dirname, _, filenames in os.walk('/home/juuso/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
import numpy as np
import pandas as pd

from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer


# Data löytyy sivuilta: 
# https://www.kaggle.com/competitions/titanic/data?select=train.csv
# https://www.kaggle.com/competitions/titanic/data?select=test.csv

# Korjatkaa alempana olevat polut oikeisiin tiedostoihin.

/home/juuso/kaggle/input/train.csv
/home/juuso/kaggle/input/test.csv


In [226]:
train_data = pd.read_csv("/home/juuso/kaggle/input/train.csv")
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [227]:
test_data = pd.read_csv("/home/juuso/kaggle/input/test.csv")
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

### Documentation

In [228]:
# Document the aims, decisions, and solutions of your data analysis directly into 
# the Jupyter Notebook as the analysis proceeds. Make the document self-explanatory.
# (0,25 grade units)

The project was started by downloading the trainset and testset from Kaggle's website. One table was printed from each dataset to verify that the downloading was successful. 

### Visualisation

In [229]:
# Describe your data. Calculate statistics, like means,
# standard deviations, and correlations.
# Draw diagrams, like histograms, scatter diagrams. 
# Visualize correlations. (0,25 grade units)

In [230]:
train_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [231]:
train_data["Ticket"].value_counts()

347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64

In [232]:
train_data["Age"].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: Age, Length: 88, dtype: int64

### Preparing data (pakollinen)

In [233]:
# Prepare your data. When and if necessary, calculate new attributes, scale attributes,
# convert categorical variables into numeric variables. (0,25 grade units)

### Preparing train set

In [234]:
train_data = train_data.drop("Cabin", axis=1)

In [235]:
sex_cat = train_data[["Sex"]]

In [236]:
ordinal_encoder = OrdinalEncoder()
sex_cat_encoded = ordinal_encoder.fit_transform(sex_cat)
sex_cat_encoded[:10]

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [237]:
train_data["Sex"] = sex_cat_encoded

In [238]:
# impute the null values of Age to median values

In [239]:
median_age = train_data["Age"].median()
train_data["Age"].fillna(median_age,inplace=True)

imputer = SimpleImputer(strategy="median")




In [240]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  1.0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  0.0  38.0      1      0   
2                             Heikkinen, Miss. Laina  0.0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.0  35.0      1      0   
4                           Allen, Mr. William Henry  1.0  35.0      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

In [241]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    float64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(3), int64(5), object(3)
memory usage: 76.7+ KB


In [242]:
# ordinal encoder to embarked

In [243]:
train_data["Embarked"].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [244]:
embarked_cat = train_data[["Embarked"]]

In [245]:
ordinal_encoder = OrdinalEncoder()
embarked_cat_encoded = ordinal_encoder.fit_transform(embarked_cat)
embarked_cat_encoded[:10]

array([[2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.]])

In [246]:
train_data["Embarked"] = embarked_cat_encoded

In [247]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  1.0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  0.0  38.0      1      0   
2                             Heikkinen, Miss. Laina  0.0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.0  35.0      1      0   
4                           Allen, Mr. William Henry  1.0  35.0      0      0   

             Ticket     Fare  Embarked  
0         A/5 21171   7.2500       2.0  
1          PC 17599  71.2833       0.0  
2  STON/O2. 3101282   7.9250       2.0  
3            113803  53.1000       2.0  
4            373450   8.0500       2.0

In [248]:
median_embarked = train_data["Embarked"].median()
train_data["Embarked"].fillna(median_embarked,inplace=True)

imputer = SimpleImputer(strategy="median")




In [249]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    float64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    float64
dtypes: float64(4), int64(5), object(2)
memory usage: 76.7+ KB


### Preparing test set

In [250]:
test_data = test_data.drop("Cabin", axis=1)

In [251]:
sex_cat = test_data[["Sex"]]

In [252]:
ordinal_encoder = OrdinalEncoder()
sex_cat_encoded = ordinal_encoder.fit_transform(sex_cat)
sex_cat_encoded[:10]

array([[1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.]])

In [253]:
test_data["Sex"] = sex_cat_encoded

In [254]:
median_age = test_data["Age"].median()
test_data["Age"].fillna(median_age,inplace=True)

imputer = SimpleImputer(strategy="median")




In [255]:
embarked_cat = test_data[["Embarked"]]

In [256]:
ordinal_encoder = OrdinalEncoder()
embarked_cat_encoded = ordinal_encoder.fit_transform(embarked_cat)
embarked_cat_encoded[:10]

array([[1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.]])

In [257]:
test_data["Embarked"] = embarked_cat_encoded

In [258]:
median_embarked = test_data["Embarked"].median()
test_data["Embarked"].fillna(median_embarked,inplace=True)

imputer = SimpleImputer(strategy="median")


In [259]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    float64
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Embarked     418 non-null    float64
dtypes: float64(4), int64(4), object(2)
memory usage: 32.8+ KB


In [278]:
test_data[test_data['Fare'].isnull()]

PassengerId  Pclass                Name  Sex   Age  SibSp  Parch Ticket  \
152         1044       3  Storey, Mr. Thomas  1.0  60.5      0      0   3701   

     Fare  Embarked  
152   NaN       2.0

In [282]:
test_data.drop(152)

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James  1.0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)  0.0   
2            894       2                     Myles, Mr. Thomas Francis  1.0   
3            895       3                              Wirz, Mr. Albert  1.0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  0.0   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf  1.0   
414         1306       1                  Oliva y Ocana, Dona. Fermina  0.0   
415         1307       3                  Saether, Mr. Simon Sivertsen  1.0   
416         1308       3                           Ware, Mr. Frederick  1.0   
417         1309       3                      Peter, Master. Michael J  1.0   

      Age  SibSp  Parch              Ticket      Fare  Embarked  
0    34.5      0      0              330911    7.8292       1.0  
1    47.0      1      0              363272    7.0000       2.0  
2    62.0      0      0              240276    9.6875       1.0  
3    27.0      0      0              315154    8.6625       2.0  
4    22.0      1      1             3101298   12.2875       2.0  
..    ...    ...    ...                 ...       ...       ...  
413  27.0      0      0           A.5. 3236    8.0500       2.0  
414  39.0      0      0            PC 17758  108.9000       0.0  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500       2.0  
416  27.0      0      0              359309    8.0500       2.0  
417  27.0      1      1                2668   22.3583       0.0  

[417 rows x 10 columns]

### Train model (pakollinen)

In [260]:
# Train two different classification models. One of them should be Random Forest or SVM.
# You can select the other one by yourselves. (0,25)
